name: Build
on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: docker://node:12
      with:
        entrypoint: yarn install
    - name: Build
      uses: docker://node:12
      with:
        entrypoint: yarn build:production
    - name: Serverless
      uses: docker://node:12
      with:
        entrypoint: npx serverless -v      