name: Build
on:
  push: { branches: [ main ] }
  pull_request: { types: [ opened, synchronize, reopened ] } 
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: node_modules-
    - uses: actions/setup-node@v1
      with: { node-version: '12' }
    - run: yarn install

  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: '12' }
      - run: |
          mkdir -p reports/unit
          touch reports/unit/unit-report
          yarn test:unit
      - uses: actions/upload-artifact@v2
        with:
          name: unit
          path: reports/unit/

  test-e2e:
    name: e2e Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: '12' }
      - run: mkdir -p reports/e2e
      - run: |
          touch reports/e2e/e2e-report
          yarn test:e2e
      - uses: actions/upload-artifact@v2
        with:
          name: e2e
          path: reports/e2e/

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [ test-unit, test-e2e ]
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: actions/download-artifact@v2
        with:
          path: reports/
      - run: |
          ls -lha reports
          ls -lha reports/unit
          ls -lha reports/e2e
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    