name: Build
on: [push, pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: docker://node:12
      with:
        entrypoint: yarn
        args: install
    - name: Build Staging
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker://node:12
      with:
        entrypoint: yarn
        args: build:staging
    - name: Build Production
      if: ${{ github.event_name == 'push' }}
      uses: docker://node:12
      with:
        entrypoint: yarn
        args: build:production
    